version: '3'
services:

  demo-web:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "supersecret"
      POSTGRES_DB: "postgres"
    command: bash -c "./wait-for-it.sh postgres:5432 -- yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - public

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "supersecret"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - public

networks:
  public:

volumes:
  db-data:
